name: CI

on: [pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: ['format-check', 'lint']
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4

    - name: check ${{ matrix.check}}
      run: |
        npm install
        npm run ${{ matrix.check}}
